name: rich_text_editor
version: 0.0.1
description: Rich Text Editor for Flutter - by Simon Lightfoot
homepage: https://github.com/slightfoot/flutter_rich_text_editor
repository: https://github.com/slightfoot/flutter_rich_text_editor

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.19.0-6.0.pre.6"

dependencies:
  #
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
